### PR TITLE
Add support for Bazel 6

### PR DESCRIPTION
**Pull request by z8v**
Related issue #42

### CODE REVIEW

**Review by aherrmann — COMMENTED** [review]
Thanks! Changes look good.
There are still some CI failures though. Looks like some labels are formatted differently in error messages with Bazel v6.

**Comment by z8v** [comment]
Yes, it seems that labels are  either prefixed with `@//` (workspace) or `@@//` (bzlmod). Maybe there is native function that we can use to remove those prefixes?

**Review by aherrmann — APPROVED** [review]
Thank you, looks good!

**Comment by aherrmann** [comment]
@z8v yes, one accepted review is enough to merge. Set the `merge-queue` label to merge it.

**Pull request merged**
